/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaswing;

import java.util.ArrayList;
import javaswing.models.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jeffe
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelCalculadora = new javax.swing.JPanel();
        jCheckBoxAdd = new javax.swing.JCheckBox();
        jLabelTitle = new javax.swing.JLabel();
        jCheckBoxSubtract = new javax.swing.JCheckBox();
        jCheckBoxMultiply = new javax.swing.JCheckBox();
        jCheckBoxDivide = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumberOne = new javax.swing.JTextField();
        jTextFieldNumberTwo = new javax.swing.JTextField();
        jButtonCalculate = new javax.swing.JButton();
        jTextFieldResult = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelFibonacci = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jButtonGenerateFibonacci = new javax.swing.JButton();
        jPanelX = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSize = new javax.swing.JTextField();
        jButtonGenerateForma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaForma = new javax.swing.JTextArea();
        Trapecio = new javax.swing.JPanel();
        jLabelHorizontalSize = new javax.swing.JLabel();
        jLabelVertivalSize = new javax.swing.JLabel();
        jTextFieldHorizontalSize = new javax.swing.JTextField();
        jTextFieldVerticalSize = new javax.swing.JTextField();
        jButtonGenerateTrapecio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTrapecio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Swing Exercices");

        jTabbedPane.setToolTipText("");

        jCheckBoxAdd.setText("Suma");
        jCheckBoxAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitle.setText("SELECCIONA LA OPERACION A REALIZAR:");

        jCheckBoxSubtract.setText("Restar");
        jCheckBoxSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubtractActionPerformed(evt);
            }
        });

        jCheckBoxMultiply.setText("Multiplicar");
        jCheckBoxMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMultiplyActionPerformed(evt);
            }
        });

        jCheckBoxDivide.setText("Dividir");
        jCheckBoxDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDivideActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("INGRESE DOS NÚMEROS:");

        jButtonCalculate.setText("Solución");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("EL RESULTADO ES:");

        javax.swing.GroupLayout jPanelCalculadoraLayout = new javax.swing.GroupLayout(jPanelCalculadora);
        jPanelCalculadora.setLayout(jPanelCalculadoraLayout);
        jPanelCalculadoraLayout.setHorizontalGroup(
            jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabelTitle))
                    .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jCheckBoxAdd)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                                            .addComponent(jTextFieldNumberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(jButtonCalculate))))
                                .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                                    .addComponent(jCheckBoxSubtract)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBoxMultiply)
                                    .addGap(25, 25, 25)
                                    .addComponent(jCheckBoxDivide)))
                            .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelCalculadoraLayout.setVerticalGroup(
            jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculadoraLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAdd)
                    .addComponent(jCheckBoxSubtract)
                    .addComponent(jCheckBoxMultiply)
                    .addComponent(jCheckBoxDivide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumberOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29))
        );

        jTabbedPane.addTab("Calculadora", jPanelCalculadora);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("INGRESE LA CANTIDAD DE ELEMENTOS:");

        jButtonGenerateFibonacci.setText("Generar");
        jButtonGenerateFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateFibonacciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFibonacciLayout = new javax.swing.GroupLayout(jPanelFibonacci);
        jPanelFibonacci.setLayout(jPanelFibonacciLayout);
        jPanelFibonacciLayout.setHorizontalGroup(
            jPanelFibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFibonacciLayout.createSequentialGroup()
                .addGroup(jPanelFibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFibonacciLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(jPanelFibonacciLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFibonacciLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonGenerateFibonacci)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanelFibonacciLayout.setVerticalGroup(
            jPanelFibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFibonacciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGenerateFibonacci)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Fibonacci", jPanelFibonacci);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("INGRESE EL TAMAÑO DE LA X:");

        jButtonGenerateForma.setText("Generar");
        jButtonGenerateForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateFormaActionPerformed(evt);
            }
        });

        jTextAreaForma.setColumns(20);
        jTextAreaForma.setRows(5);
        jScrollPane1.setViewportView(jTextAreaForma);

        javax.swing.GroupLayout jPanelXLayout = new javax.swing.GroupLayout(jPanelX);
        jPanelX.setLayout(jPanelXLayout);
        jPanelXLayout.setHorizontalGroup(
            jPanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXLayout.createSequentialGroup()
                .addGroup(jPanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelXLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2))
                    .addGroup(jPanelXLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelXLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButtonGenerateForma)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelXLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanelXLayout.setVerticalGroup(
            jPanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGenerateForma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("X", jPanelX);

        jLabelHorizontalSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHorizontalSize.setText("INGRESE EL TAMAÑO HORIZONTAL:");

        jLabelVertivalSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVertivalSize.setText("INGRESE EL TAMAÑO VERTICAL:");

        jButtonGenerateTrapecio.setText("Generar");
        jButtonGenerateTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateTrapecioActionPerformed(evt);
            }
        });

        jTextAreaTrapecio.setColumns(20);
        jTextAreaTrapecio.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTrapecio);

        javax.swing.GroupLayout TrapecioLayout = new javax.swing.GroupLayout(Trapecio);
        Trapecio.setLayout(TrapecioLayout);
        TrapecioLayout.setHorizontalGroup(
            TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrapecioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHorizontalSize)
                    .addComponent(jLabelVertivalSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldHorizontalSize, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jTextFieldVerticalSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonGenerateTrapecio)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrapecioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrapecioLayout.setVerticalGroup(
            TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrapecioLayout.createSequentialGroup()
                .addGroup(TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrapecioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHorizontalSize)
                            .addComponent(jTextFieldHorizontalSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVertivalSize)
                            .addComponent(jTextFieldVerticalSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TrapecioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonGenerateTrapecio)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Trapecio", Trapecio);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddActionPerformed
        if (jCheckBoxAdd.isSelected() && (jCheckBoxSubtract.isSelected() || jCheckBoxMultiply.isSelected() || jCheckBoxDivide.isSelected())) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un elemento por favor", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxAddActionPerformed

    private void jCheckBoxSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubtractActionPerformed
        if (jCheckBoxSubtract.isSelected() && (jCheckBoxAdd.isSelected() || jCheckBoxMultiply.isSelected() || jCheckBoxDivide.isSelected())) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un elemento por favor", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxSubtractActionPerformed

    private void jCheckBoxMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMultiplyActionPerformed
        if (jCheckBoxMultiply.isSelected() && (jCheckBoxSubtract.isSelected() || jCheckBoxAdd.isSelected() || jCheckBoxDivide.isSelected())) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un elemento por favor", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxMultiplyActionPerformed

    private void jCheckBoxDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDivideActionPerformed
        if (jCheckBoxDivide.isSelected() && (jCheckBoxSubtract.isSelected() || jCheckBoxMultiply.isSelected() || jCheckBoxAdd.isSelected())) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un elemento por favor", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxDivideActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed

        if (jCheckBoxAdd.isSelected() && (jCheckBoxSubtract.isSelected() || jCheckBoxMultiply.isSelected() || jCheckBoxDivide.isSelected())
                || jCheckBoxSubtract.isSelected() && (jCheckBoxAdd.isSelected() || jCheckBoxMultiply.isSelected() || jCheckBoxDivide.isSelected())
                || jCheckBoxMultiply.isSelected() && (jCheckBoxSubtract.isSelected() || jCheckBoxAdd.isSelected() || jCheckBoxDivide.isSelected())
                || jCheckBoxDivide.isSelected() && (jCheckBoxSubtract.isSelected() || jCheckBoxMultiply.isSelected() || jCheckBoxAdd.isSelected())) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un elemento por favor", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Calculadora calculadora = new Calculadora();

        double NumberOne = Double.parseDouble(jTextFieldNumberOne.getText());
        double NumberTwo = Double.parseDouble(jTextFieldNumberTwo.getText());

        calculadora.setNumberOne(NumberOne);
        calculadora.setNumberTwo(NumberTwo);

        if (jCheckBoxAdd.isSelected()) {
            calculadora.add();
        }
        if (jCheckBoxSubtract.isSelected()) {
            calculadora.subtract();
        }
        if (jCheckBoxMultiply.isSelected()) {
            calculadora.multiply();
        }
        if (jCheckBoxDivide.isSelected()) {
            calculadora.divide();
        }

        String result = String.valueOf(calculadora.getResult());

        jTextFieldResult.setText(result);

    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jButtonGenerateFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateFibonacciActionPerformed
        // TODO add your handling code here:

        String text = jTextFieldN.getText();
        if (text.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un número.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int N = Integer.parseInt(text);

        if (N <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese números mayores a cero.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Fibonacci fibo = new Fibonacci();

        fibo.setLimit(N);

        fibo.generateSequence();

        ArrayList sequence = fibo.getSequence();

        for (int i = 0; i < sequence.size(); i++) {
            int position = i + 1;
            JOptionPane.showMessageDialog(null, "En la posición " + position + ": " + sequence.get(i), "Fibonnaci", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGenerateFibonacciActionPerformed

    private void jButtonGenerateFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateFormaActionPerformed
        // TODO add your handling code here:

        String text = jTextFieldSize.getText();
        if (text.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un número.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int N = Integer.parseInt(text);

        if (N <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese números mayores a cero.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        X x = new X();

        x.setSize(N);

        x.generateForma();

        String forma = x.getForma();

        jTextAreaForma.setText(forma);

    }//GEN-LAST:event_jButtonGenerateFormaActionPerformed

    private void jButtonGenerateTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateTrapecioActionPerformed
        // TODO add your handling code here:
        String horizontal = jTextFieldHorizontalSize.getText();
        String vertical = jTextFieldVerticalSize.getText();
        if (horizontal.equals("") || vertical.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int H = Integer.parseInt(horizontal);
        int V = Integer.parseInt(vertical);

        if (H <= 0 || V <= 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese números mayores a cero.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Trapecio trapecio = new Trapecio();

        trapecio.setHorizontalSise(H);
        trapecio.setVerticalSize(V);

        trapecio.generateForma();

        String forma = trapecio.getForma();

        jTextAreaTrapecio.setText(forma);
    }//GEN-LAST:event_jButtonGenerateTrapecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Trapecio;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonGenerateFibonacci;
    private javax.swing.JButton jButtonGenerateForma;
    private javax.swing.JButton jButtonGenerateTrapecio;
    private javax.swing.JCheckBox jCheckBoxAdd;
    private javax.swing.JCheckBox jCheckBoxDivide;
    private javax.swing.JCheckBox jCheckBoxMultiply;
    private javax.swing.JCheckBox jCheckBoxSubtract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHorizontalSize;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVertivalSize;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelCalculadora;
    private javax.swing.JPanel jPanelFibonacci;
    private javax.swing.JPanel jPanelX;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaForma;
    private javax.swing.JTextArea jTextAreaTrapecio;
    private javax.swing.JTextField jTextFieldHorizontalSize;
    private javax.swing.JTextField jTextFieldN;
    private javax.swing.JTextField jTextFieldNumberOne;
    private javax.swing.JTextField jTextFieldNumberTwo;
    private javax.swing.JTextField jTextFieldResult;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JTextField jTextFieldVerticalSize;
    // End of variables declaration//GEN-END:variables
}
